### ISSUE TITLE
MissingMethodException occurs when using a newer version (5.0.2) of Lightinject 

### ISSUE THREAD

**Issue by DmitriiGaidukov** [sbosell/Hangfire.LightInject#2]
The System.MissingMethodException is being logged continuously, though It seems like jobs do they work quite ok. But this exception happens in the DisposeScope() method of the LightInjecterScope class, and I've scared to come across some scope-related issues in the future. So I've tried to change a little the LightInjecterScope class, saving the scope in a field in order to have access to scope from the DisposeScope().
For now the exceptions’ve ceased and  It looks like all is good. Though I’m not certain..

public override void DisposeScope()
{
            /*var scope = _container.ScopeManagerProvider.GetScopeManager().CurrentScope;
            if (scope != null)
            {
                _container.EndCurrentScope();
                scope.Dispose();
            }*/

	    if (_scope != null)
            {
                _scope.Dispose();
            }
}

**Comment by GODBS** [comment]
Got the same issue

**Comment by sbosell** [comment]
Please submit a PR.

**Comment by DmitriiGaidukov** [comment]
Ready.  #3

**Comment by sbosell** [comment]
I will try to review it today.

**Comment by geirsagberg** [comment]
@sbosell Any plans on merging this PR?

**Comment by sbosell** [comment]
Done.

**Comment by dmytroshunkov** [comment]
@sbosell It seems to be, that fixed version is not uploaded to nuget yet?

**Comment by sbosell** [comment]
@dmitryshunkov thanks for letting me know.  This is all automated on appveyor (setup years ago) and it isn't publishing for some reason.  Their support is great so hopefully, it will be worked out soon.

**Comment by AndyGJones** [comment]
Seems to be still out of date on nuget (or I've broken something else!) - any update on getting the package published?

**Comment by sbosell** [comment]
Sorry it took me so long, I had to figure out why appveyor was failing/etc. It is published now.

**Comment by AndyGJones** [comment]
No problem, thanks for your work, much appreciated!
